import re
from pathlib import Path
from typing import Any, cast

import yaml  # type: ignore[import-untyped]

try:
    import tomllib
except ModuleNotFoundError:
    import tomli as tomllib


REQUIRED_PACKAGE_DATA = {
    "py.typed",
    "_js_runtime_support.js",
    "packages.json",
    "std/*.geno",
}


def _publish_workflow() -> dict[str, Any]:
    repo_root = Path(__file__).resolve().parents[2]
    return cast(
        dict[str, Any],
        yaml.safe_load(
            (repo_root / ".github" / "workflows" / "publish.yml").read_text(
                encoding="utf-8"
            )
        ),
    )


def _publish_workflow_jobs():
    return _publish_workflow()["jobs"]


def _step_by_name(job: dict, name: str) -> dict:
    return next(step for step in job["steps"] if step.get("name") == name)


def _step_names(job: dict) -> list[str | None]:
    return [step.get("name") for step in job["steps"]]


def _pyproject() -> dict[str, Any]:
    repo_root = Path(__file__).resolve().parents[2]
    return cast(
        dict[str, Any],
        tomllib.loads((repo_root / "pyproject.toml").read_text(encoding="utf-8")),
    )


def test_distribution_name_avoids_the_unrelated_pypi_geno_project():
    assert _pyproject()["project"]["name"] == "geno-lang"


def test_package_discovery_excludes_test_suite():
    package_find = _pyproject()["tool"]["setuptools"]["packages"]["find"]

    assert "geno.tests*" in package_find["exclude"]
    assert _pyproject()["tool"]["setuptools"]["include-package-data"] is False


def test_publish_workflow_hash_locks_build_tools_and_validates_metadata():
    jobs = _publish_workflow_jobs()

    job = jobs["build"]
    install = _step_by_name(job, "Install build tools")["run"]
    validate = _step_by_name(job, "Validate artifact metadata")

    assert install == (
        "python -m pip install --require-hashes -r requirements-release.lock"
    )
    assert validate["run"] == "python -m twine check --strict dist/*"

    repo_root = Path(__file__).resolve().parents[2]
    release_lock = (repo_root / "requirements-release.lock").read_text(encoding="utf-8")
    assert "autogenerated by pip-compile with Python 3.11" in release_lock
    for tool in ("build", "setuptools", "twine", "wheel"):
        assert f"{tool}==" in release_lock
    for linux_dependency in ("importlib-metadata", "jeepney", "secretstorage"):
        assert f"{linux_dependency}==" in release_lock
    assert "--hash=sha256:" in release_lock


def test_publish_workflow_validates_and_smokes_before_artifact_upload():
    jobs = _publish_workflow_jobs()

    build_steps = _step_names(jobs["build"])
    assert build_steps.index("Build package") < build_steps.index(
        "Validate artifact metadata"
    )
    assert build_steps.index("Validate artifact metadata") < build_steps.index(
        "Smoke test wheel"
    )
    assert build_steps.index("Validate artifact metadata") < build_steps.index(
        "Smoke test sdist"
    )
    assert build_steps.index("Smoke test wheel") < build_steps.index(
        "Upload tested distributions"
    )
    assert build_steps.index("Smoke test sdist") < build_steps.index(
        "Upload tested distributions"
    )


def test_publish_workflow_requires_pypi_environment_approval():
    jobs = _publish_workflow_jobs()

    assert jobs["publish"]["environment"] == "pypi"


def test_publish_workflow_has_release_build_publish_verify_chain():
    jobs = _publish_workflow_jobs()

    assert jobs["build"]["needs"] == "release-check"
    assert jobs["publish"]["needs"] == "build"
    assert jobs["verify"]["needs"] == "publish"
    assert (
        _step_by_name(jobs["release-check"], "Run release gate")["run"]
        == "make release-check PYTHON=python"
    )


def test_publish_workflow_checks_tag_before_release_gate():
    jobs = _publish_workflow_jobs()
    steps = jobs["release-check"]["steps"]
    names = [step.get("name") for step in steps]

    assert names.index("Verify release tag matches package version") < names.index(
        "Run release gate"
    )
    tag_check = _step_by_name(
        jobs["release-check"], "Verify release tag matches package version"
    )
    assert "--tag" in tag_check["run"]


def test_publish_workflow_scopes_oidc_to_shell_free_publish_job():
    workflow = _publish_workflow()
    jobs = workflow["jobs"]

    assert workflow["permissions"] == {"contents": "read"}
    assert jobs["publish"]["permissions"]["id-token"] == "write"
    assert all(
        value != "write"
        for name, value in jobs["publish"]["permissions"].items()
        if name != "id-token"
    )
    assert all(
        job_name == "publish" or job.get("permissions", {}).get("id-token") != "write"
        for job_name, job in jobs.items()
    )

    publish_steps = jobs["publish"]["steps"]
    assert len(publish_steps) == 2
    assert all("run" not in step for step in publish_steps)
    for step in publish_steps:
        action, separator, ref = step["uses"].partition("@")
        assert separator == "@", action
        assert len(ref) == 40 and all(char in "0123456789abcdef" for char in ref)


def test_publish_workflow_transfers_the_smoked_artifact_without_rebuild():
    jobs = _publish_workflow_jobs()
    build_steps = _step_names(jobs["build"])
    publish_steps = _step_names(jobs["publish"])
    upload = _step_by_name(jobs["build"], "Upload tested distributions")
    download = _step_by_name(jobs["publish"], "Download tested distributions")

    assert build_steps.count("Build package") == 1
    assert "Build package" not in publish_steps
    assert upload["with"]["name"] == download["with"]["name"]
    assert upload["with"]["path"] == "dist/"
    assert download["with"] == {"name": "python-distributions", "path": "dist/"}


def test_docker_build_context_and_copy_are_allowlisted():
    repo_root = Path(__file__).resolve().parents[2]
    dockerfile = (repo_root / "Dockerfile").read_text(encoding="utf-8")
    dockerignore = (repo_root / ".dockerignore").read_text(encoding="utf-8")
    dependabot = yaml.safe_load(
        (repo_root / ".github" / "dependabot.yml").read_text(encoding="utf-8")
    )

    from_lines = [line for line in dockerfile.splitlines() if line.startswith("FROM ")]
    assert len(from_lines) == 2
    assert all(
        re.fullmatch(
            r"FROM python:3\.11-slim@sha256:[0-9a-f]{64} AS (builder|runtime)",
            line,
        )
        for line in from_lines
    )
    assert "COPY --chown=geno:geno . /app" not in dockerfile
    assert "COPY --from=builder" in dockerfile
    assert "python -m twine check --strict dist/*" in dockerfile

    ignore_lines = set(dockerignore.splitlines())
    assert dockerignore.splitlines()[2] == "*"
    assert "!geno/**" not in ignore_lines
    assert not any("geno/tests" in line for line in ignore_lines)
    assert {
        "!pyproject.toml",
        "!requirements.lock",
        "!requirements-release.lock",
        "!geno/server.py",
        "!geno/_darwin_resource.py",
        "!geno/cli/run.py",
        "!geno/std/List.geno",
    } <= ignore_lines
    assert any(
        update.get("package-ecosystem") == "docker" and update.get("directory") == "/"
        for update in dependabot["updates"]
    )


def test_installed_smoke_accepts_empty_public_catalog():
    from scripts import smoke_installed_geno

    smoke_installed_geno._assert_runtime_assets_available()


def test_setuptools_package_data_includes_runtime_assets():
    pyproject = _pyproject()

    package_data = set(pyproject["tool"]["setuptools"]["package-data"]["geno"])

    assert package_data >= REQUIRED_PACKAGE_DATA


def test_declared_runtime_assets_exist_on_disk():
    package_root = Path(__file__).resolve().parents[1]

    for pattern in REQUIRED_PACKAGE_DATA:
        if "*" in pattern:
            if "/" in pattern:
                parent, glob_pat = pattern.rsplit("/", 1)
            else:
                parent, glob_pat = ".", pattern
            matches = list((package_root / parent).glob(glob_pat))
            assert matches, f"no files match '{pattern}' under {package_root}"
        else:
            assert (package_root / pattern).is_file(), (
                f"missing declared asset '{pattern}' under {package_root}"
            )
